# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Application_config = debug
  Renderer_config = debug

else ifeq ($(config),release)
  Application_config = release
  Renderer_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Application Renderer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Application: Renderer
ifneq (,$(Application_config))
	@echo "==== Building Application ($(Application_config)) ===="
	@${MAKE} --no-print-directory -C Application -f Makefile config=$(Application_config)
endif

Renderer:
ifneq (,$(Renderer_config))
	@echo "==== Building Renderer ($(Renderer_config)) ===="
	@${MAKE} --no-print-directory -C Renderer -f Makefile config=$(Renderer_config)
endif

clean:
	@${MAKE} --no-print-directory -C Application -f Makefile clean
	@${MAKE} --no-print-directory -C Renderer -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Application"
	@echo "   Renderer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"